 @hostname = localhost:3000

### Get all transfers
GET http://{{hostname}}/api/transfers
Content-Type: application/json

### Get transfer by ID
GET http://{{hostname}}/api/transfers/1
Content-Type: application/json

### Create new transfer
POST http://{{hostname}}/api/transfers
Content-Type: application/json

{
"amount": 100,
"sourceId": 1,
"targetId": 2
}

### Create new transfer (Error, wrong participant ID)
POST http://{{hostname}}/api/transfers
Content-Type: application/json

{
"amount": 100,
"sourceId": 1,
"targetId": 99
}