 @hostname = localhost:3000

### Get all expenses
GET http://{{hostname}}/api/expenses
Content-Type: application/json

### Get expense by ID
GET http://{{hostname}}/api/expenses/1
Content-Type: application/json

### Create new expense
POST http://{{hostname}}/api/expenses
Content-Type: application/json

{
"description": "Office Supplies",
"amount": 45.99,
"payerId": 1,
"participantIds": [1, 2]
}

### Create new expense (Error, wrong participant ID)
POST http://{{hostname}}/api/expenses
Content-Type: application/json

{
"description": "Office Supplies",
"amount": 45.99,
"payerId": 1,
"participantIds": [1, 99]
}